### PR TITLE
Configurator Form

### PR DESCRIPTION
**Pull request by Locutus73**
A MiSTer Configurator form for configuring MiSTer.ini, Samba and WiFi settings, and downloading Cores, and Extras (Filters, Fonts, Cheats, Game Boy Palettes, Updater, Scripts, SoundFont Installer).
It can be opened with two lines of code:
ConfiguratorForm objConfiguratorForm = new ConfiguratorForm("E:\\", false);
objConfiguratorForm.ShowDialog();
If you use the constructor with two parameters, the first is for setting the actual MiSTer SD location (where files will be placed) and the second is for locking (disabling) the combo used for changing this directory in the user interface.

### CODE REVIEW

**Comment by alfishe** [comment]
No offense, but it's inappropriate code style

**Comment by Locutus73** [comment]
Absolutely no offense.
Can you elaborate?

**Comment by Locutus73** [comment]
@alfishe if you give me indications of things you don’t like, I can change them and make a new pull request. We can start with few points (if you prefer) and iterate until you like the style. 

Thank you in advance.

**Comment by alfishe** [comment]
1) Replace repetitive full namespace qualifiers like "System.IO.Path." with using System.IO.Path;
2) String constants instead of using literals everywhere ("Stop", all urls, param names)
3) String.Equals instead of ==
4) Check for String.IsNullOrEmpty before use
5) All parse results should be checked before use
6) Precompiled regex -> to readonly class members

It's just about readability and maintainability. Good for initial prototype, but not for long time support. 
Please start reworking and polishing so it can be used by other developers =)

**Comment by Locutus73** [comment]
Indeed it was a quickie, just to test the ground and see if you and Sorg liked the idea of the post install setup. Now that I have a confirmation, I’ll clean the code following your inputs. 
By the way, compiling the WinForm as a stand-alone exe I managed to pack it into self contained Linux and Mac applications embedding mono (so no preinstalled mono required). 
If you want to take a look:
https://github.com/Locutus73/MiSTerConfiguratorTEST

**Comment by alfishe** [comment]
Yes, probably it's much better idea to have separate tool and as max - put link from installer (only if correspondent configurator binary found in the same folder). Cleaner concept and easier to maintain

**Comment by sorgelig** [comment]
I like idea to start external configurator by button/link from main installer. So you guys won't fight each other ;)
Anyway installer copy whatever is in files folder. So it's pretty much independent job. Also configurator no need to be written exactly in C#. It can be even native C code.

**Comment by Locutus73** [comment]
@sorgelig We are not fighting at all, @alfishe politely gave some constructive hints I’m implementing right now. The WinForm is written in a way that it can be included as a panel in the SD-Installer or it can be a separate exe. No fighting at all, the choice is yours. I was thinking to an additional panel included in the SD-Installer for Windows and a separate application for Mac and Win, but, again, the choice is yours.
In the meantime I’m applying @alfishe recommendations, do you want me to make a pull request here or have a separate repository?

**Comment by sorgelig** [comment]
I was kidding :)
It's better to make a separate exe as alfishe proposed. So, main installer will need just button to launch a configurator. Then you will write your own exe in the way you like and i will bundle both executables in the release.

**Comment by Locutus73** [comment]
Fine, so I'll make a separate repository,
@alfishe When I upload the new repository, any recommendation will be more than welcome.

Thank you in advance.
Regards.

**Pull request closed without merging**
